"""
Django settings for fx_project project.
Generated by 'django-admin startproject' using Django X.Y.Z.
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR now points to the outer 'fx_project' folder containing manage.py
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/X.Y/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# You can leave the default generated key for local development
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'fallback-key-for-local-only') #key removed 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [] # Leave empty for local development


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'forecaster', # <-- ADD THIS LINE: Register our 'forecaster' app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fx_project.urls' # Points to the inner fx_project/urls.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # --- UPDATE THIS ---
        # Tell Django to look for a 'templates' folder in the BASE_DIR (project root)
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # --- END UPDATE ---
        'APP_DIRS': True, # Also look for templates inside app folders (though we aren't using this)
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fx_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/X.Y/ref/settings/#databases
# We don't need a real database, SQLite is fine.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/X.Y/ref/settings/#auth-password-validators
# Leave the default AUTH_PASSWORD_VALIDATORS block as generated by Django


# Internationalization
# https://docs.djangoproject.com/en/X.Y/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/X.Y/howto/static-files/
STATIC_URL = 'static/'
# Optional: If you add CSS/JS later, uncomment and use this
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


# Default primary key field type
# https://docs.djangoproject.com/en/X.Y/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Project Specific Settings ---
# --- ADD THIS LINE ---
# Define the path to your machine learning models folder
MODEL_ML_PATH = os.path.join(BASE_DIR, 'models')
# --- END ADD ---